defmodule VyaasaCampus.AI.BehavioralEngine do
  @moduledoc """
  Native Elixir port of the Python behavioral interview engine
  (`/home/geekbull-ravi/zed/vyaasa/engine.py`).

  Design goals:
    * 4 phases — `:greeting`, `:presenting`, `:answering`, `:finished`.
    * ZERO LLM calls for flow; everything uses hard-coded templates.
    * ONE LLM call at the end, only for report generation (temperature 0.0).
    * Scenarios loaded statically from `priv/data/behavioral_scenarios.json`
      and picked at random per round.
    * Deterministic pre-flight quality guard that short-circuits the LLM
      with a zero-score report when every answer is gibberish / empty.
    * Post-LLM safety ceiling: if N of 3 answers are insufficient, every
      competency is capped proportionally regardless of what the LLM said.

  State is held per-session in a map (managed by LiveView assigns).
  """

  alias VyaasaCampus.AI.GroqClient

  require Logger

  # ============================================================================
  # CONFIG
  # ============================================================================

  # Aligned with the dev-behavioral reference engine (~/zed/vyaasa): 2 scenarios,
  # report generated by gpt-oss-120b.
  @scenarios_per_interview 2
  @orchestrator_model "openai/gpt-oss-120b"
  # One STAR follow-up probe per scenario.
  @probe_model "openai/gpt-oss-120b"
  @probe_fallback "Could you walk me through one specific thing you did, and what the outcome was?"

  @star_probe_system """
  You are Vyaasa, a warm, professional behavioral interviewer. The candidate just
  answered a behavioral scenario. Choose ONE probe mode based on answer quality:

  MODE 1 — RECOVERY (invalid/unusable answer: gibberish, under ~10 meaningful
  words, unrelated, or "I don't know"). Ask them to retry the original scenario:
  under 30 words, briefly reference the scenario topic, warm and non-judgmental,
  no STAR terminology.

  MODE 2 — AUTHENTICITY PROBE (suspiciously polished / AI-generated: round
  metrics, flawless STAR, no friction/failure, emotionally flat). Ask ONE
  question easy for someone who lived it but hard to fabricate (a moment of
  friction, an emotional dimension, a human detail, a retrospective, or a
  consequence). Under 35 words, conversational, not accusatory, never reveal you
  are probing, use "you"/"your".

  MODE 3 — STAR FOLLOW-UP (normal answer). Identify the WEAKEST or MISSING element
  among Situation, Task, Action, Result and ask EXACTLY ONE short follow-up
  targeting it. Under 35 words; do NOT use the words STAR/situation/task/action/
  result; use "you"/"your"; warm. If all four are strong, ask what they would do
  differently next time.

  GENERAL RULES: Output the follow-up question and NOTHING ELSE — one question,
  no preamble, no acknowledgment. If the answer lacks substance, use MODE 1.
  """
  @report_temperature 0.0
  @report_timeout 60_000

  @scenarios_path "priv/data/behavioral_scenarios.json"

  # ---- Deterministic answer-quality tunables (mirror engine.py lines 538–540)
  @min_words_per_answer 15
  @min_unique_meaningful 6
  @min_chars_per_answer 40

  @stopwords MapSet.new(~w(a an the and or but if to of in on at for with is am are was were be been
                being it its this that these those i you we he she they them my your our so
                as do did does have has had will would could should can may might just very
                um uh like))

  @competency_keys [
    "work_ethics_and_reliability",
    "teamwork_and_collaboration",
    "adaptability_and_learning",
    "leadership_potential",
    "communication_skills"
  ]

  # Weights for the overall score (normalized weighted average of the five
  # competencies). Uniform 0.20 today → identical to a straight average; this is
  # the single knob to re-weight competency importance later. Mirrors the
  # dev-behavioral reference (~/zed/vyaasa COMPETENCY_WEIGHTS).
  @competency_weights %{
    "work_ethics_and_reliability" => 0.20,
    "teamwork_and_collaboration" => 0.20,
    "adaptability_and_learning" => 0.20,
    "leadership_potential" => 0.20,
    "communication_skills" => 0.20
  }

  @competency_labels %{
    "work_ethics_and_reliability" => "Work Ethics & Reliability",
    "teamwork_and_collaboration" => "Teamwork & Collaboration",
    "adaptability_and_learning" => "Adaptability & Learning",
    "leadership_potential" => "Leadership Potential",
    "communication_skills" => "Cultural Fit & Emotional Intelligence"
  }

  @rating_keys [
    {"work_ethics_and_reliability", "work_ethics_rating", "work_ethics_reasoning"},
    {"teamwork_and_collaboration", "teamwork_rating", "teamwork_reasoning"},
    {"adaptability_and_learning", "adaptability_rating", "adaptability_reasoning"},
    {"leadership_potential", "leadership_rating", "leadership_reasoning"},
    {"communication_skills", "communication_rating", "communication_reasoning"}
  ]

  # ============================================================================
  # TEMPLATES (zero LLM calls for flow)
  # ============================================================================

  @greeting_template """
  Hi <NAME>! 👋 I'm **Vyaasa**, your Situational & Behavioral Interviewer.

  I'll walk you through **2 scenarios** — one at a time. For each one, please answer using the **STAR** format:

  • **S — Situation:** Set the scene. What was happening?
  • **T — Task:** What were *you* responsible for?
  • **A — Action:** What did *you* specifically do? (use "I", not "we")
  • **R — Result:** What was the outcome? Numbers help if you have them.

  **Example:** "During my final-year project *(S)*, we had four weeks to ship a working prototype *(T)*. I owned the backend, set weekly milestones, and paired with a teammate on the tough bits *(A)*. We demoed on time and placed second in the college showcase *(R)*."

  After each answer, I'll ask **one short follow-up** to dig a little deeper. You can speak your answer or type it — whatever feels natural. Take your time. Click **Proceed** when you're ready! 🚀
  """

  @greeting_spoken_template """
  Hi <NAME>! I'm Vyaasa, your Situational and Behavioral Interviewer. I'll give you 2 scenarios. Answer each one using the STAR method: Situation, Task, Action, and Result. After each answer I'll ask one short follow-up. You can speak or type your answers. Click Proceed when you're ready!
  """

  @scenario_prompt_template "Round <CURRENT> of <TOTAL> — here are two scenarios. Pick the one you'd prefer to answer."

  @round_transition_template "Great answer, <NAME>! Round <CURRENT> of <TOTAL> — here are two more scenarios. Pick one."

  @completion_template "Thank you, <NAME>! 🎉 You've completed both scenarios. Your behavioral assessment report is being prepared — it'll be ready in just a moment."

  @completion_spoken_template "Thank you, <NAME>! You have completed both scenarios. Your behavioral assessment report is ready."

  # ============================================================================
  # REPORT SYSTEM PROMPT (verbatim from engine.py lines 444–530)
  # ============================================================================

  @report_system_prompt ~s"""
  You are a senior HR expert evaluating a final-year graduate student's behavioral interview. Your scores are used for hiring decisions across thousands of candidates, so they MUST be consistent, calibrated, and honest. Do NOT give pity points.

  The candidate answered three situational/behavioral scenarios using the STAR method. Assess them purely on the quality, depth, and honesty of those answers.

  ═══════════════════════════════════════════════════════════════════════════
  SCORING BANDS (apply uniformly to every competency, 0–100 scale)
  ═══════════════════════════════════════════════════════════════════════════

    0 – 9    NO ANSWER / GIBBERISH. Empty, nonsensical ("asdf", "ags", "idk"),
             single word, or completely off-topic. Award this without hesitation.
   10 – 24   EXTREMELY WEAK. A sentence or two with no STAR structure, no
             specifics, no ownership. E.g. "I would just talk to them."
   25 – 44   WEAK. Some engagement with the question but vague, generic,
             missing 3+ STAR components, no concrete actions or outcomes.
   45 – 64   BELOW AVERAGE. Attempts STAR but only 1–2 components are solid;
             actions are generic; result is absent or hand-waved.
   65 – 79   AVERAGE / COMPETENT. All four STAR components present but thin.
             Shows basic understanding. Expected floor for a prepared fresher.
   80 – 94   GOOD. Clear STAR, specific actions using "I", measurable or
             concrete results, genuine ownership, relevant to the competency.
   95 – 100  EXCELLENT. Vivid situation, crisp task, differentiated actions,
             quantified results, self-reflection, and clear evidence of the
             competency in action.

  ═══════════════════════════════════════════════════════════════════════════
  HARD RULES — VIOLATIONS MAKE THE REPORT INVALID
  ═══════════════════════════════════════════════════════════════════════════

  1. **GIBBERISH GUARD.** If an answer is under ~15 meaningful words, is
     gibberish (e.g. "ags", "asdf", "hello test"), or does not engage with
     the scenario at all, EVERY competency tied to that scenario scores
     0–9. Do NOT rescue the score by speculating what the candidate
     "might have meant." Score what is written, nothing else.

  2. **COMPETENCY NOT ADDRESSED.** If a competency is barely mentioned or
     entirely absent across the answers, score it 0–15 — not 40, not
     30. Absent evidence = absent score.

  3. **NO PITY POINTS.** Never award 20+ simply because the candidate
     showed up. The floor for "made an attempt" is not 20; the floor is
     whatever the rubric says for the actual quality on display.

  4. **SCORE MUST MATCH REASONING.** If reasoning describes a weak or
     missing response, the score MUST be in the 0–44 (weak or worse) band.
     High score with weak reasoning (or vice versa) is a hard failure.

  5. **CITE EVIDENCE.** Every `reasoning` field must quote or paraphrase
     a concrete moment from the candidate's answer. If you cannot cite
     anything, the score is 0–9 and the reasoning should say so
     ("Candidate wrote only 'ags' — no evidence to assess.").

  6. **FRESHER CALIBRATION ≠ LENIENCY.** Do not penalise lack of
     *industry* experience. DO penalise lack of structure, specificity,
     ownership, or effort. A prepared fresher with a well-told college
     project story can legitimately score 80+.

  7. **JSON ONLY.** Return a valid JSON object. No markdown fences, no
     preamble. DO NOT include `overall_score` — it is computed from the
     five competency scores.

  ═══════════════════════════════════════════════════════════════════════════
  CALIBRATION EXAMPLES (internalise these anchors)
  ═══════════════════════════════════════════════════════════════════════════

  • Answer = "ags"                                     → all competencies 0–5
  • Answer = "i would talk to them"                    → all competencies 10–20
  • Answer = "I had a group project and we finished it"→ 25–40
  • Answer = 3–4 sentences of generic STAR              → 62–74
  • Answer = clear STAR with specific "I" actions and a concrete outcome → 80–88
  • Answer = above + quantified result + reflection    → 90–97

  IMPORTANT — `communication_rating` measures CULTURAL FIT & EMOTIONAL
  INTELLIGENCE: the values, authenticity, emotional maturity, self-awareness,
  and collaboration style the candidate reveals in their answers — NOT verbal
  fluency or polish. Score that field on that basis.

  ═══════════════════════════════════════════════════════════════════════════
  OUTPUT FORMAT — return EXACTLY this JSON structure
  ═══════════════════════════════════════════════════════════════════════════

  {
    "candidate_name": "<str>",
    "work_ethics_rating": <int 0-100>,   "work_ethics_reasoning": "<str citing evidence>",
    "teamwork_rating": <int 0-100>,      "teamwork_reasoning": "<str citing evidence>",
    "adaptability_rating": <int 0-100>,  "adaptability_reasoning": "<str citing evidence>",
    "leadership_rating": <int 0-100>,    "leadership_reasoning": "<str citing evidence>",
    "communication_rating": <int 0-100>, "communication_reasoning": "<str citing evidence>",
    "summary": "<3–5 sentence executive summary grounded in the actual answers>",
    "strengths": ["<evidence-backed strength>", ...],
    "areas_for_development": ["<specific, actionable area>", ...]
  }
  """

  # ============================================================================
  # SESSION LIFECYCLE
  # ============================================================================

  @doc """
  Creates a new interview session. `full_name` is used in greeting / completion
  templates and in the final report. `student_id` is kept for bookkeeping.
  """
  def new_session(session_id, student_id, full_name) when is_binary(session_id) do
    %{
      session_id: session_id,
      student_id: student_id,
      full_name: full_name,
      phase: :greeting,
      messages: [],
      scenarios_completed: [],
      current_options: nil,
      active_scenario: nil,
      pending_entry: nil,
      probe_question: nil,
      report: nil
    }
  end

  # Backwards-compat arity for old call sites; fills full_name with "Candidate".
  def new_session(session_id), do: new_session(session_id, nil, "Candidate")

  @doc """
  Advances the session by one turn.

    * With `message == nil` on `:greeting` → emits greeting + spoken text.
    * On `:greeting` with any message → interprets as "Proceed" and moves
      to first scenario pair.
    * On `:presenting` with message "1"/"2" or `scenario_choice: 1|2`
      → locks the chosen scenario.
    * On `:answering` with message → records answer and advances
      (next round or final report).

  Returns `{:ok, new_state, response_map}`.
  """
  def process_turn(state, message \\ nil, scenario_choice \\ nil) do
    VyaasaCampus.AI.Tracing.span("behavioral.turn", state[:session_id], fn ->
      do_process_turn(state, message, scenario_choice)
    end)
  end

  defp do_process_turn(state, message, scenario_choice) do
    state =
      if is_binary(message) and String.trim(message) != "" do
        %{state | messages: state.messages ++ [%{role: "user", content: String.trim(message)}]}
      else
        state
      end

    state =
      case state.phase do
        :greeting when is_nil(message) or message == "" -> handle_greeting(state)
        :greeting -> handle_proceed(state)
        :presenting -> handle_presenting(state, message, scenario_choice)
        :answering -> handle_answering(state, message)
        :probing -> handle_probing(state, message)
        :finished -> state
      end

    {:ok, state, response_for(state)}
  end

  # ---- backwards-compat shim used by contexts/behavioral.ex
  @doc false
  def process_message(state, message \\ nil), do: process_turn(state, message)

  @doc """
  Force-end the session early (used when proctoring auto-finalizes on too many
  integrity violations). Scores whatever rounds are already complete; if none
  are complete there is nothing to evaluate, so it signals `:terminated`.

    * `{:ok, finished_state, response}` — report generated from completed rounds
    * `{:terminated, state}`           — no completed rounds, no score
  """
  def force_finish(state) do
    VyaasaCampus.AI.Tracing.span("behavioral.force_finish", state[:session_id], fn -> do_force_finish(state) end)
  end

  defp do_force_finish(state) do
    cond do
      state.phase == :finished ->
        {:ok, state, response_for(state)}

      state.scenarios_completed == [] ->
        {:terminated, state}

      true ->
        finished = finish_interview(state)
        {:ok, finished, response_for(finished)}
    end
  end

  # ============================================================================
  # PHASE HANDLERS
  # ============================================================================

  defp handle_greeting(state) do
    name = first_name(state.full_name)
    content = @greeting_template |> String.replace("<NAME>", name)
    spoken = @greeting_spoken_template |> String.replace("<NAME>", name)

    %{
      state
      | messages: state.messages ++ [%{role: "assistant", content: content, spoken: spoken}]
    }
  end

  defp handle_proceed(state) do
    present_next_round(state)
  end

  defp handle_presenting(state, message, scenario_choice) do
    options = state.current_options || []

    {state, options} =
      if options == [] do
        state = populate_next_options(state)
        {state, state.current_options || []}
      else
        {state, options}
      end

    choice = resolve_choice(scenario_choice, message)

    cond do
      choice not in [1, 2] or choice > length(options) ->
        msg = %{
          role: "assistant",
          content: "Please pick either Scenario 1 or Scenario 2 to continue.",
          spoken: nil
        }

        %{state | messages: state.messages ++ [msg]}

      true ->
        chosen = Enum.at(options, choice - 1)
        question = chosen["question"] || ""

        msg = %{role: "assistant", content: question, spoken: question}

        %{
          state
          | phase: :answering,
            active_scenario: chosen,
            current_options: nil,
            messages: state.messages ++ [msg]
        }
    end
  end

  defp handle_answering(state, message) do
    active = state.active_scenario
    answer = (message || "") |> to_string() |> String.trim()

    cond do
      is_nil(active) ->
        present_next_round(state)

      answer == "" ->
        msg = %{
          role: "assistant",
          content: "I didn't receive an answer. Could you share your response?",
          spoken: nil
        }

        %{state | messages: state.messages ++ [msg]}

      true ->
        # Record the initial STAR answer, then ask ONE follow-up probe. The
        # scenario isn't "completed" (and the round counter doesn't advance)
        # until the probe is answered in handle_probing/2.
        probe = generate_star_probe(active["question"] || "", answer)

        pending = %{
          "scenario_id" => active["scenario_id"],
          "scenario_question" => active["question"],
          "dimensions" => active["dimensions"] || [],
          "candidate_response" => answer,
          "probe_question" => probe
        }

        msg = %{role: "assistant", content: probe, spoken: probe}

        %{
          state
          | pending_entry: pending,
            probe_question: probe,
            phase: :probing,
            messages: state.messages ++ [msg]
        }
    end
  end

  # Records the answer to the follow-up probe, finalises the scenario entry,
  # then advances to the next round or the final report.
  defp handle_probing(state, message) do
    answer = (message || "") |> to_string() |> String.trim()

    cond do
      answer == "" ->
        msg = %{
          role: "assistant",
          content: "Could you share a bit more on that?",
          spoken: "Could you share a bit more on that?"
        }

        %{state | messages: state.messages ++ [msg]}

      is_nil(state.pending_entry) ->
        # Defensive — shouldn't happen; recover by moving on.
        present_next_round(%{state | phase: :presenting})

      true ->
        entry = Map.put(state.pending_entry, "probe_response", answer)

        state = %{
          state
          | scenarios_completed: state.scenarios_completed ++ [entry],
            pending_entry: nil,
            active_scenario: nil,
            probe_question: nil
        }

        done = length(state.scenarios_completed)

        if done < @scenarios_per_interview do
          present_next_round(state)
        else
          finish_interview(state)
        end
    end
  end

  # One Groq call (fast model) → a single targeted STAR follow-up question.
  # Falls back to a generic probe on any failure so the interview never stalls.
  defp generate_star_probe(scenario, answer) do
    messages = [
      %{role: "system", content: @star_probe_system},
      %{
        role: "user",
        content: "/no_think\n\nSCENARIO ASKED:\n#{String.trim(scenario)}\n\nCANDIDATE'S ANSWER:\n#{String.trim(answer)}"
      }
    ]

    case GroqClient.chat(messages,
           model: @probe_model,
           temperature: 0.3,
           reasoning_effort: "low",
           timeout: @report_timeout
         ) do
      {:ok, %{"content" => raw}} when is_binary(raw) ->
        probe =
          raw
          # qwen emits <think>…</think> reasoning — strip it before using the text.
          |> then(&Regex.replace(~r/<think>.*?<\/think>/s, &1, ""))
          |> String.trim()
          |> String.trim("\"")
          |> String.trim("'")
          |> then(&Regex.replace(~r/^(follow[-\s]?up|question|q)\s*[:\-]\s*/i, &1, ""))
          |> String.trim()

        if probe == "", do: @probe_fallback, else: probe

      _ ->
        @probe_fallback
    end
  rescue
    _ -> @probe_fallback
  end

  defp finish_interview(state) do
    report = generate_report(state)
    name = first_name(state.full_name)

    completion_msg = %{
      role: "assistant",
      content: @completion_template |> String.replace("<NAME>", name),
      spoken: @completion_spoken_template |> String.replace("<NAME>", name)
    }

    %{
      state
      | phase: :finished,
        report: report,
        messages: state.messages ++ [completion_msg]
    }
  end

  # ============================================================================
  # SCENARIO SELECTION
  # ============================================================================

  defp present_next_round(state) do
    state = populate_next_options(state)
    opts = state.current_options || []
    done = length(state.scenarios_completed)

    cond do
      opts == [] ->
        msg = %{
          role: "assistant",
          content: "Something went wrong loading scenarios. Please restart.",
          spoken: nil
        }

        %{state | messages: state.messages ++ [msg]}

      true ->
        options_text =
          opts
          |> Enum.with_index(1)
          |> Enum.map_join("\n\n", fn {opt, i} ->
            "**Scenario #{i}:** #{opt["question"]}"
          end)

        intro =
          if done == 0 do
            @scenario_prompt_template
            |> String.replace("<CURRENT>", "1")
            |> String.replace("<TOTAL>", to_string(@scenarios_per_interview))
          else
            @round_transition_template
            |> String.replace("<NAME>", first_name(state.full_name))
            |> String.replace("<CURRENT>", to_string(done + 1))
            |> String.replace("<TOTAL>", to_string(@scenarios_per_interview))
          end

        msg = %{
          role: "assistant",
          content: "#{intro}\n\n#{options_text}",
          # Silent — scenario choice screen has no TTS audio.
          spoken: nil
        }

        %{state | phase: :presenting, messages: state.messages ++ [msg]}
    end
  end

  defp populate_next_options(state) do
    all_scenarios = load_scenarios()
    used_ids = Enum.map(state.scenarios_completed, & &1["scenario_id"])

    available =
      Enum.reject(all_scenarios, fn s ->
        Map.get(s, "scenario_id") in used_ids
      end)

    available = if length(available) < 2, do: all_scenarios, else: available

    cond do
      length(available) < 2 ->
        Logger.error("BEHAVIORAL | Not enough scenarios in pool | session=#{state.session_id}")
        %{state | current_options: []}

      true ->
        seeds = Enum.take_random(available, 2)

        options =
          Enum.map(seeds, fn s ->
            %{
              "id" => "opt_" <> random_id(),
              "scenario_id" => Map.get(s, "scenario_id"),
              "title" => Map.get(s, "title", ""),
              "dimensions" => Map.get(s, "dimensions", []),
              "question" => (Map.get(s, "description") || "") |> String.trim()
            }
          end)

        %{state | current_options: options}
    end
  end

  # ============================================================================
  # REPORT GENERATION — the single LLM call
  # ============================================================================

  defp generate_report(state) do
    name = state.full_name || "Candidate"
    student_id = state.student_id
    completed = state.scenarios_completed
    quality = summarize_quality(completed)

    Logger.info(
      "BEHAVIORAL | Quality check | session=#{state.session_id} insufficient=#{quality.insufficient_count}/#{length(completed)} avg_words=#{Float.round(quality.avg_words_per_scenario, 1)}"
    )

    cond do
      quality.all_insufficient ->
        Logger.warning("BEHAVIORAL | All answers insufficient, issuing zero-score report | session=#{state.session_id}")

        gibberish_report(name, student_id, completed, quality)

      true ->
        call_llm_and_build_report(state, name, student_id, completed, quality)
    end
  end

  defp call_llm_and_build_report(state, name, student_id, completed, quality) do
    scenarios_block = build_scenarios_block(completed, quality)

    transcript =
      state.messages
      |> Enum.map_join("\n", fn m -> "#{String.upcase(m.role)}: #{m.content}" end)

    user_prompt = """
    CANDIDATE NAME: #{name}
    CONTEXT: Final-year graduate student (fresher).

    #{scenarios_block}

    FULL INTERVIEW TRANSCRIPT:
    #{transcript}
    """

    messages = [
      %{role: "system", content: @report_system_prompt},
      %{role: "user", content: user_prompt}
    ]

    case GroqClient.chat(messages,
           model: @orchestrator_model,
           temperature: @report_temperature,
           timeout: @report_timeout,
           response_format: %{"type" => "json_object"},
           reasoning_effort: "low"
         ) do
      {:ok, %{"content" => raw}} ->
        case raw |> GroqClient.strip_reasoning() |> GroqClient.extract_json() do
          {:ok, data} ->
            build_report_from_llm(data, name, student_id, completed, quality)

          {:error, reason} ->
            Logger.error("BEHAVIORAL | Report JSON parse failed: #{inspect(reason)}")
            empty_report(name, student_id, completed, inspect(reason))
        end

      {:error, reason} ->
        Logger.error("BEHAVIORAL | Report LLM failed: #{inspect(reason)}")
        empty_report(name, student_id, completed, inspect(reason))
    end
  end

  defp build_scenarios_block(completed, quality) do
    lines =
      completed
      |> Enum.with_index(1)
      |> Enum.map(fn {c, i} ->
        dims =
          case Map.get(c, "dimensions") do
            list when is_list(list) and list != [] -> Enum.join(list, ", ")
            _ -> "N/A"
          end

        question = (Map.get(c, "scenario_question") || "") |> String.trim()

        response =
          (Map.get(c, "candidate_response") || "")
          |> String.trim()
          |> maybe_truncate(1500)

        probe_q = (Map.get(c, "probe_question") || "") |> String.trim()
        probe_r = (Map.get(c, "probe_response") || "") |> String.trim() |> maybe_truncate(1000)

        probe_block =
          if probe_q != "" do
            "\n  Follow-up:  #{probe_q}\n  Follow-up Response: #{if probe_r == "", do: "(no response)", else: probe_r}"
          else
            ""
          end

        q = Enum.at(quality.per_scenario, i - 1, %{insufficient: false})

        quality_tag =
          if q[:insufficient] do
            """

              ⚠ QUALITY FLAG: this answer is insufficient (words=#{q[:word_count]}, unique_meaningful=#{q[:unique_meaningful]}). Per the gibberish guard, score every competency tied to this scenario 0–9.
            """
            |> String.trim_trailing()
          else
            ""
          end

        """
        Scenario #{i}:
          Dimensions: #{dims}
          Question:   #{question}
          Response:   #{response}#{probe_block}#{quality_tag}
        """
        |> String.trim_trailing()
      end)

    "COMPLETED SCENARIOS (#{length(completed)}):\n\n" <> Enum.join(lines, "\n\n")
  end

  defp build_report_from_llm(data, name, student_id, completed, quality) do
    ratings =
      @rating_keys
      |> Enum.map(fn {dest, score_key, reason_key} ->
        score = data |> Map.get(score_key, 0) |> to_int() |> clamp(0, 100)
        reasoning = data |> Map.get(reason_key, "") |> to_string() |> String.trim()
        {dest, %{"score" => score, "reasoning" => reasoning}}
      end)
      |> Enum.into(%{})

    ratings = apply_safety_ceiling(ratings, quality, length(completed))

    # Overall = normalized weighted average per @competency_weights.
    {weighted_sum, weight_total} =
      Enum.reduce(@competency_keys, {0.0, 0.0}, fn k, {ws, wt} ->
        w = Map.get(@competency_weights, k, 0.0)
        {ws + (ratings[k]["score"] || 0) * w, wt + w}
      end)

    overall = if weight_total > 0.0, do: round(weighted_sum / weight_total), else: 0

    report = %{
      "candidate_name" => to_string(Map.get(data, "candidate_name") || name),
      "student_id" => student_id,
      "overall_score" => overall,
      "ratings" => ratings,
      "summary" => data |> Map.get("summary", "") |> to_string() |> String.trim(),
      "strengths" => clean_list(Map.get(data, "strengths")),
      "areas_for_development" => clean_list(Map.get(data, "areas_for_development")),
      "completed_scenarios" => completed,
      "raw_text" => ""
    }

    Map.put(report, "raw_text", format_report_text(report))
  end

  # Proportional post-LLM cap: if 1/3 answers usable → ceiling 33, 2/3 → 66.
  defp apply_safety_ceiling(ratings, quality, total) when total > 0 do
    usable = total - quality.insufficient_count

    if usable < total do
      ceiling = max(0, round(100 * usable / total) - 5)

      Enum.map(ratings, fn {k, %{"score" => s} = r} ->
        if s > ceiling, do: {k, %{r | "score" => ceiling}}, else: {k, r}
      end)
      |> Enum.into(%{})
    else
      ratings
    end
  end

  defp apply_safety_ceiling(ratings, _quality, _total), do: ratings

  # ============================================================================
  # DETERMINISTIC QUALITY CHECK (mirrors engine.py _analyze_answer_quality)
  # ============================================================================

  @doc false
  def analyze_answer_quality(text) do
    raw = (text || "") |> to_string() |> String.trim()
    lower = String.downcase(raw)

    words = Regex.scan(~r/[a-z']+/, lower) |> List.flatten()

    meaningful =
      Enum.filter(words, fn w -> not MapSet.member?(@stopwords, w) and String.length(w) > 1 end)

    unique_meaningful = MapSet.new(meaningful) |> MapSet.size()

    is_empty = String.length(raw) == 0

    is_too_short =
      String.length(raw) < @min_chars_per_answer or length(words) < @min_words_per_answer

    is_low_info = unique_meaningful < @min_unique_meaningful

    is_gibberish =
      (length(words) <= 2 and String.length(raw) < 20) or
        (length(words) >= 1 and
           not Enum.any?(Enum.take(words, 3), &String.match?(&1, ~r/[aeiou]/)))

    insufficient = is_empty or is_too_short or is_low_info or is_gibberish

    %{
      raw_length: String.length(raw),
      word_count: length(words),
      unique_meaningful: unique_meaningful,
      is_empty: is_empty,
      is_too_short: is_too_short,
      is_low_info: is_low_info,
      is_gibberish: is_gibberish,
      insufficient: insufficient
    }
  end

  defp summarize_quality(completed) do
    per_scenario =
      Enum.map(completed, fn c -> analyze_answer_quality(Map.get(c, "candidate_response", "")) end)

    n = length(per_scenario)
    n_safe = if n == 0, do: 1, else: n
    insufficient_count = Enum.count(per_scenario, & &1.insufficient)
    total_words = per_scenario |> Enum.map(& &1.word_count) |> Enum.sum()

    %{
      per_scenario: per_scenario,
      insufficient_count: insufficient_count,
      all_insufficient: n > 0 and insufficient_count == n,
      any_insufficient: insufficient_count > 0,
      total_words: total_words,
      avg_words_per_scenario: total_words / n_safe
    }
  end

  # ============================================================================
  # FALLBACK REPORTS
  # ============================================================================

  defp gibberish_report(name, student_id, completed, quality) do
    reason =
      "The candidate did not provide a substantive answer to any scenario " <>
        "(e.g. responses were empty, a single token, or under #{@min_words_per_answer} words). " <>
        "There is no evidence on which to assess this competency."

    ratings =
      @competency_keys
      |> Enum.map(fn k -> {k, %{"score" => 0, "reasoning" => reason}} end)
      |> Enum.into(%{})

    avg_words = Float.round(quality.avg_words_per_scenario, 0) |> trunc()

    report = %{
      "candidate_name" => name,
      "student_id" => student_id,
      "overall_score" => 0,
      "ratings" => ratings,
      "summary" =>
        "Assessment could not be evaluated: the candidate's responses to the scenarios " <>
          "were empty or non-substantive (average #{avg_words} words per answer, well below the " <>
          "minimum required for evaluation). We recommend the candidate retake the assessment " <>
          "and answer each scenario in the STAR format with a clear situation, task, specific " <>
          "actions they took, and the outcome.",
      "strengths" => [],
      "areas_for_development" => [
        "Provide substantive answers that engage with each scenario.",
        "Use the STAR structure: Situation, Task, Action, Result.",
        "Describe specific actions taken, using 'I' rather than 'we'.",
        "Aim for at least 80–120 words per scenario."
      ],
      "completed_scenarios" => completed,
      "raw_text" => ""
    }

    Map.put(report, "raw_text", format_report_text(report))
  end

  defp empty_report(name, student_id, completed, error) do
    ratings =
      @competency_keys
      |> Enum.map(fn k ->
        {k, %{"score" => 0, "reasoning" => "Report unavailable — evaluation service error."}}
      end)
      |> Enum.into(%{})

    report = %{
      "candidate_name" => name,
      "student_id" => student_id,
      "overall_score" => 0,
      "ratings" => ratings,
      "summary" => "Report could not be generated: #{error}",
      "strengths" => [],
      "areas_for_development" => [],
      "completed_scenarios" => completed,
      "raw_text" => ""
    }

    Map.put(report, "raw_text", format_report_text(report))
  end

  # ============================================================================
  # TEXT REPORT FORMATTING (mirrors engine.py _format_report_text)
  # ============================================================================

  defp format_report_text(report) do
    ratings = Map.get(report, "ratings", %{})

    competency_lines =
      @competency_keys
      |> Enum.map_join("\n", fn k ->
        r = Map.get(ratings, k, %{})
        label = Map.get(@competency_labels, k)
        score = Map.get(r, "score", 0)
        "  • #{String.pad_trailing(label, 32)}  #{pad_score(score)}/100"
      end)

    reasoning_lines =
      @competency_keys
      |> Enum.map_join("\n", fn k ->
        r = Map.get(ratings, k, %{})
        label = Map.get(@competency_labels, k)
        "  • #{label}: #{Map.get(r, "reasoning", "")}"
      end)

    strengths = format_list(Map.get(report, "strengths", []))
    development = format_list(Map.get(report, "areas_for_development", []))

    """
    ================================================================================
    COMPREHENSIVE BEHAVIORAL ASSESSMENT REPORT
    ================================================================================

    CANDIDATE: #{Map.get(report, "candidate_name", "N/A")}

    COMPETENCY RATINGS (Scale: 0–100)
    ────────────────────────────────────────────────────────────────────────────────
    #{competency_lines}

    OVERALL SCORE:                    #{Map.get(report, "overall_score", 0)}/100
    ────────────────────────────────────────────────────────────────────────────────
    REASONING
    ────────────────────────────────────────────────────────────────────────────────
    #{reasoning_lines}

    ────────────────────────────────────────────────────────────────────────────────
    EXECUTIVE SUMMARY
    ────────────────────────────────────────────────────────────────────────────────
    #{Map.get(report, "summary", "")}

    ────────────────────────────────────────────────────────────────────────────────
    KEY STRENGTHS
    ────────────────────────────────────────────────────────────────────────────────
    #{strengths}

    ────────────────────────────────────────────────────────────────────────────────
    DEVELOPMENT AREAS
    ────────────────────────────────────────────────────────────────────────────────
    #{development}

    Thank you for participating in this behavioral assessment.
    """
  end

  defp pad_score(n) when is_integer(n), do: n |> Integer.to_string() |> String.pad_leading(3)
  defp pad_score(_), do: "  0"

  defp format_list([]), do: "(none)"

  defp format_list(items) when is_list(items) do
    items
    |> Enum.with_index(1)
    |> Enum.map_join("\n", fn {item, i} -> "#{i}. #{item}" end)
  end

  defp format_list(_), do: ""

  # ============================================================================
  # SCENARIOS LOADER
  # ============================================================================

  @doc false
  def load_scenarios do
    path = Application.app_dir(:vyaasa_campus, @scenarios_path)

    with {:ok, content} <- File.read(path),
         {:ok, %{"scenarios" => scenarios}} <- Jason.decode(content) do
      scenarios
    else
      _ ->
        Logger.error("BEHAVIORAL | Could not load scenarios from #{path}")
        []
    end
  end

  # ============================================================================
  # RESPONSE BUILDER (shape the LiveView/API consumes)
  # ============================================================================

  defp response_for(state) do
    {reply, spoken_reply} = last_assistant_text(state.messages)
    active = state.active_scenario || %{}

    # During the probe phase the "current question" the candidate answers is the
    # follow-up probe, not the scenario.
    scenario_question =
      if state.phase == :probing, do: state.probe_question, else: active["question"]

    %{
      "session_id" => state.session_id,
      "reply" => reply,
      "spoken_reply" => spoken_reply,
      "scenario_options" => state.current_options,
      "scenario_question" => scenario_question,
      "is_followup" => state.phase == :probing,
      "scenarios_count" => length(state.scenarios_completed),
      "phase" => Atom.to_string(state.phase),
      "interview_finished" => state.phase == :finished,
      "report" => state.report
    }
  end

  defp last_assistant_text(messages) do
    messages
    |> Enum.reverse()
    |> Enum.find(&(&1.role == "assistant"))
    |> case do
      nil -> {"", nil}
      %{content: c, spoken: s} -> {c, s}
      %{content: c} -> {c, nil}
    end
  end

  # ============================================================================
  # HELPERS
  # ============================================================================

  defp first_name(nil), do: "there"
  defp first_name(""), do: "there"

  defp first_name(full_name) when is_binary(full_name) do
    case String.split(full_name, ~r/\s+/, trim: true) do
      [first | _] -> first
      _ -> "there"
    end
  end

  defp first_name(_), do: "there"

  defp resolve_choice(choice, _message) when choice in [1, 2], do: choice

  defp resolve_choice(_, message) when is_binary(message) do
    case Regex.run(~r/^\s*(?:scenario\s*)?([12])\b/i, String.trim(message)) do
      [_, n] -> String.to_integer(n)
      _ -> nil
    end
  end

  defp resolve_choice(_, _), do: nil

  defp random_id, do: :crypto.strong_rand_bytes(3) |> Base.encode16(case: :lower)

  defp maybe_truncate(s, max) when byte_size(s) > max do
    String.slice(s, 0, max) |> String.trim_trailing() |> Kernel.<>("…")
  end

  defp maybe_truncate(s, _), do: s

  defp to_int(n) when is_integer(n), do: n
  defp to_int(n) when is_float(n), do: trunc(n)

  defp to_int(n) when is_binary(n) do
    case Integer.parse(n) do
      {v, _} -> v
      :error -> 0
    end
  end

  defp to_int(_), do: 0

  defp clamp(n, lo, hi) when is_integer(n), do: n |> max(lo) |> min(hi)
  defp clamp(_, lo, _), do: lo

  defp clean_list(nil), do: []

  defp clean_list(list) when is_list(list) do
    list
    |> Enum.map(fn v -> v |> to_string() |> String.trim() end)
    |> Enum.reject(&(&1 == ""))
  end

  defp clean_list(_), do: []
end