import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :vyaasa_campus, VyaasaCampusWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  debug_errors: false,
  code_reloader: false,
  check_origin: [System.get_env("PHX_HOST") || "example.com"]

# Disable Swoosh Local Memory Storage (SMTP adapter used, configured in runtime.exs)
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Force SSL in production
config :vyaasa_campus, VyaasaCampusWeb.Endpoint, force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
